name: Install pip dependencies
description: Create virtual environment and install Python dependencies

inputs:
  service-path:
    description: Path to python-greetings repository
    required: true

runs:
  using: composite
  steps:
    - name: Create venv and install requirements
      shell: powershell
      working-directory: ${{ inputs.service-path }}
      run: |
        Write-Host "Creating Python virtual environment..."
        python -m venv venv

        Write-Host "Installing dependencies from requirements.txt..."
        .\venv\Scripts\python.exe -m pip install --upgrade pip
        .\venv\Scripts\python.exe -m pip install -r requirements.txt